#!/bin/sh
# -*- sh -*-

: << =cut

=head1 NAME

temper - Plugin that reads temperature from a TEMPer1 USB device.

=head1 MAGIC MARKERS

 #%# family=auto
 #%# capabilities=autoconf

=cut

. $MUNIN_LIBDIR/plugins/plugin.sh

if [ "$1" = "autoconf" ]; then
	echo yes
	exit 0
fi

if [ "$1" = "config" ]; then
	echo 'graph_title USB Temperature'
	echo 'graph_vlabel degrees Celsius'
	echo 'graph_args --base 1000 -l 0 -u 45'
	echo 'graph_category sensors'
	echo 'temp.label Temp'
	echo 'temp.warning 35.0'
	echo 'temp.critical 40.0'

	exit 0
fi

echo "temp.value $(temper)"

